#!/bin/sh
export TERM=xterm-256color
red=$( tput setaf 1 );
normal=$( tput sgr 0);
echo
echo "${red}-------------------------------------------------------------------------------
    ___         __  __               _                __
   /   | __  __/ /_/ /_  ____  _____(_)___  ___  ____/ /
  / /| |/ / / / __/ __ \/ __ \/ ___/ /_  / / _ \/ __  /
 / ___ / /_/ / /_/ / / / /_/ / /  / / / /_/  __/ /_/ /
/_/ _||\__,_/\__/_/ /_/\____/_/  /_/ /___/\___/\__,_/
   /   | _____________  __________
  / /| |/ ___/ ___/ _ \/ ___/ ___/
 / ___ / /__/ /__/  __(__  |__  )
/_/__||\___/\__||\___/_||_/____/
  / __ \____  / /_  __/ /
 / / / / __ \/ / / / / /
/ /_/ / / / / / /_/ /_/
\____/_/ /_/_/\__, (_)
             /____/

ALERT! You are logging into a secured device! Your IP Address, Login Time, and
Username have been noted and have been sent to the server administrator!

 This service is restricted to authorized users only. All activities on this
system are logged.

 Unauthorized access will be fully investigated and reported to the
appropriate law enforcement agencies.

--------------------------------------------------------------------------------${normal}"
